---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: CHANGE_ME
  namespace: backup-review
  labels:
    app: postgresql-data-snapshot
spec:
  storageClassName: CHANGE_ME
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: CHANGE_ME
  resources:
    requests:
      storage: 1Gi
