---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: CHANGE_ME
  namespace: backup-review
  labels:
    app: postgresql-data-clone
spec:
  storageClassName: CHANGE_ME
  accessModes:
    - ReadWriteOnce
  dataSource:
    kind: PersistentVolumeClaim
    name: CHANGE_ME
  resources:
    requests:
      storage: 1Gi
