---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: CHANGE_ME
  namespace: backup-review
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: CHANGE_ME
  resources:
    requests:
      storage: 1Gi
