- name: Install and configure a customized web server
  hosts: webservers
  gather_facts: False
  tasks:

    - name: Install httpd package
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Validate firewall
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Template out httpd configuration file
      template:
        src: apache_httpdconf.j2
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: '0444'

    - name: Template out httpd index file
      template:
        src: apache_indexhtml.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0444'

    - name: Start and enable httpd daemon
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Start and enab firewalld daemon
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Open http firewalld port
      firewalld:
        service: http
        immediate: yes
        permanent: yes
        state: enabled
