apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: expanded-local-block
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: cluster.ocs.openshift.io/openshift-storage
          operator: In
          values:
          - ""
  storageClassDevices:
    - storageClassName: localblock
      volumeMode: Block
      devicePaths:
        - CHANGE ME
        - CHANGE ME
        - CHANGE ME
