kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "external-mysql-service"
subsets:
  -
    addresses:
      -
        ip: "134.119.191.185"
    ports:
      -
        port: 3306
        name: "mysql"
