---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-restore
  namespace: backup-volume
  labels:
    app: postgresql-data-snapshot
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: postgresql-data
  resources:
    requests:
      storage: 1Gi
