---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: famous-quotes-db
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi
