---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: CHANGE_ME
  namespace: openshift-image-registry
spec:
  accessModes:
   - CHANGE_ME
  resources:
    requests:
      storage: CHANGE_ME
  storageClassName: CHANGE_ME
  volumeMode: Filesystem
