---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-tool
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi
