---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-backup
  namespace: backup-application
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi
